# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%=ENV['DATABASE_NAME']%>
  pool: 5
  username: <%=ENV['DATABASE_USER']%>
  password: <%=ENV['DATABASE_PASS']%>
  socket: /tmp/mysql.sock
